name: R-CMD-check fedora

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rhub/fedora-clang-devel:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'

      - name: Install system dependencies
        run: |
          # Install necessary system dependencies here
          # For example:
          sudo dnf install -y libcurl-devel openssl-devel

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck, any::XML
          pak-version: devel # See https://github.com/r-lib/actions/issues/559

      - uses: r-lib/actions/check-r-package@v2
