on:
  push:
    branches:
      '**'
  pull_request:
    branches: [master]

name: R-CMD-check-Fedora

jobs:
  R-CMD-check-Fedora:
    runs-on: ubuntu-latest
    container:
      image: rhub/fedora-clang-devel:latest
    name: Fedora (R-devel)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          dnf -y update
          dnf -y install pandoc gdal gdal-devel proj proj-devel \
          libcurl-devel openssl-devel libxml2-devel \
          bzip2-devel zlib-devel xz-devel pcre2-devel readline-devel libicu-devel \
          libjpeg-turbo-devel libpng-devel libtiff-devel cairo-devel pango-devel \
          texlive-latex texlive-fonts-extra

      - name: Install R package dependencies
        run: |
          Rscript -e "install.packages(c('rcmdcheck', 'remotes', 'XML'), repos = 'https://cloud.r-project.org')"

      - name: Run R CMD check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error')"
